FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY . .

RUN mkdir -p /app/logs && chmod 777 /app/logs

ENV PYTHONPATH=/app

# fastapi
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
